# Generated by Django 4.2.5 on 2023-09-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email_alter_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(default='migrated', max_length=200),
            preserve_default=False,
        ),
    ]
