# Generated by Django 4.2.5 on 2023-10-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_skill_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-created']},
        ),
    ]
