# Generated by Django 4.2.5 on 2023-10-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_options'),
        ('projects', '0008_alter_review_unique_together_alter_review_body'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
