# Generated by Django 4.2.5 on 2023-10-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_review_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vote_positive',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
